image::https://avatars.githubusercontent.com/u/71876378?s=200&v=4[Teragrep Logo]

= doc_01 – Documentation for Teragrep

The official documentation for Teragrep, accessed on https://docs.teragrep.com[docs.teragrep.com].

This repository primarily serves as an issue collector. Currently, the only way to contribute to Teragrep's documentation is to https://github.com/teragrep/doc_01/issues/new/choose[open a new issue] when you notice gaps in the documentation.  

== Features

Our documentation website currently offers documentation for:

* Data Processing Language (DPL) commands
* How to use Teragrep user interface

The documentation website is generated with https://github.com/asciidoctor[Asciidoctor] and https://antora.org/[Antora].

== Contributing

You can involve yourself with our project by https://github.com/teragrep/doc_01/issues/new/choose[opening an issue] or submitting a pull request. 

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories. 

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories. 
